services:
  backend:
    build:
      context: ./backend
    ports:
      - "10100:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "14200:80"
