# Reference
int1=https://mvax.dx-int1-common.digital.vodafoneaws.co.uk
dev1=https://mvax.dx-dev1-common.digital.vodafoneaws.co.uk
qc1=https://mvax.dx-qc1-common.digital.vodafoneaws.co.uk
prodsup=https://mvax.dx-prodsup-common.digital.vodafoneaws.co.uk
qc2=https://mvax.dx-qc2-common.digital.vodafoneaws.co.uk
qcx=https://mvax.dx-qcx-common.digital.vodafoneaws.co.uk
pat1-common=https://mvax.dx-pat1-common.digital.vodafoneaws.co.uk
pat2=https://mvax.dx-pat2-common.digital.vodafoneaws.co.uk
prod1-common=https://mvax.vodafone.co.uk
prod1-blue=https://mvax.mvax-preprod.svc.vodafoneaws.co.uk
local=https://localhost:8443

CROURL=https://localhost:8002
url= https://mvax.dx-qc1-common.digital.vodafoneaws.co.uk